# This file is used to preprocess dataset, available for any HH-RLHF format datasets
import os
from dataclasses import dataclass, field
from typing import Optional, cast
from tqdm import tqdm
import random

from transformers import (
    HfArgumentParser,
    AutoTokenizer,
    AutoModelForSequenceClassification,
    AutoModelForCausalLM,
)

import torch

from hidden_context.train_llm_preference_model import (
    DataSubset,
    get_hh_rlhf_dataset,
    concatenate_datasets,
)

from copy import deepcopy

import numpy as np

@dataclass
class ScriptArguments:
    output_dir: Optional[str] = field(
        metadata={"help": "Directory where the new dataset will be stored."},
    )
    data_path: str = field(
        metadata={"help": "Directory where the original data is stored."}
    )
    data_subset: str = field(
        default="helpful",
        metadata={
            "help": "Which subset of the data to use. You can choose between"
                    "'helpful', or 'harmless'."
        },
    )
    data_split: str = field(
        default="test",
        metadata={
            "help": "Which split of the data to use. You can choose between"
                    "'train', or 'test'."
        },
    )
    dataset_size: int = field(
        default=0,
        metadata={"help": "The size of the subset of the data to use"},
    )
    model_type: str = field(
        default="none",
        metadata={
            "help": "You can choose between 'gpt2', 'llama', or 'none'."
        }
    )
    model_name_or_path: Optional[str] = field(
        default=None,
        metadata={
            "help": "Path to a local model directory or huggingface model name."
        }
    )
    embed_dim: int = field(
        default=1024,
        metadata={
            "help": "Dimension of the embeddings generated by LLM."
        }
    )
    max_length: int = field(
        default=1024,
        metadata={
            "help": "Maximum token length of the inputs."
        }
    )
    with_embeddings: bool = field(
        default=True,
        metadata={
            "help": "Whether the embeddings are generated during pre-processing."
        }
    )
    synthetic_dataset: bool = field(
        default=False,
        metadata={
            "help": "Whether a synthetic dataset is used."
        }
    )
    other_subsets: str = field(default=None)

class SimpleHHRLHFPreprocessor(object):
    def __init__(self, tokenizer, **tokenizer_kwargs):
        self.tokenizer = tokenizer
        self.tokenizer_kwargs = tokenizer_kwargs

    def __call__(self, examples):
        new_examples: dict = {
            "input_ids_chosen": [],
            "attention_mask_chosen": [],
            "input_ids_rejected": [],
            "attention_mask_rejected": [],
        }
        for chosen, rejected in zip(examples["chosen"], examples["rejected"]):
            tokenized_chosen = self.tokenizer(chosen, **self.tokenizer_kwargs)
            tokenized_rejected = self.tokenizer(rejected, **self.tokenizer_kwargs)

            new_examples["input_ids_chosen"].append(tokenized_chosen["input_ids"])
            new_examples["attention_mask_chosen"].append(tokenized_chosen["attention_mask"])
            new_examples["input_ids_rejected"].append(tokenized_rejected["input_ids"])
            new_examples["attention_mask_rejected"].append(tokenized_rejected["attention_mask"])

        return new_examples

def generate_embeddings_with_llm(args, input_dataset=None):
    """
    This function is used to generate fixed embeddings for inputs from original dataset.
    """
    if not args.synthetic_dataset:
        data_subset = cast(DataSubset, args.data_subset)
        input_dataset = get_hh_rlhf_dataset(
            data_subset,
            args.data_split,
            args.dataset_size,
            data_path=args.data_path,
            use_subset_as_dir=True,
            other_subsets=args.other_subsets,
        )

    if args.model_type == "gpt2":
        model_id = args.model_name_or_path if args.model_name_or_path else "gpt2"
        tokenizer = AutoTokenizer.from_pretrained(model_id, use_auth_token=True)
        model = AutoModelForSequenceClassification.from_pretrained(
            model_id, num_labels=args.embed_dim, torch_dtype=torch.bfloat16,
            device_map="auto" #Added by me
        )
        model.score.weight.data *= 0.01
    elif args.model_type == "llama" or args.model_type == "meta-llama/Llama-2-7b-hf":
        model_id = args.model_name_or_path if args.model_name_or_path else "meta-llama/Llama-2-7b-hf"
        tokenizer = AutoTokenizer.from_pretrained(model_id, use_auth_token=True, add_eos_token=False)
        model = AutoModelForCausalLM.from_pretrained(
            model_id, torch_dtype=torch.bfloat16,
            device_map="auto" #Added by me

        )
    elif args.model_type == "llama3" or args.model_type == "meta-llama/Meta-Llama-3-8B-Instruct":
        model_id = args.model_name_or_path if args.model_name_or_path else "meta-llama/Meta-Llama-3-8B-Instruct"
        tokenizer = AutoTokenizer.from_pretrained(model_id, use_auth_token=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_id, torch_dtype=torch.bfloat16,
            device_map="auto" #Added by me
        )
    else:
        return input_dataset
#    model.to("cuda") Removed by me

    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id
    tokenizer.padding_side = "right"

    model.config.pad_token_id = tokenizer.pad_token_id
    dataset_size = len(input_dataset)
    print(dataset_size)

    preprocessed_dataset = input_dataset.map(
        SimpleHHRLHFPreprocessor(tokenizer),
        batched=True,
        num_proc=24,
        remove_columns=input_dataset.column_names,
        load_from_cache_file=False,
    )

    input_dataset = input_dataset.filter(
        lambda example, idx: len(preprocessed_dataset[idx]["input_ids_chosen"]) <= args.max_length
                             and len(preprocessed_dataset[idx]["input_ids_rejected"]) <= args.max_length,
        with_indices=True
    )
    preprocessed_dataset = preprocessed_dataset.filter(
        lambda example: len(example["input_ids_chosen"]) <= args.max_length
                        and len(example["input_ids_rejected"]) <= args.max_length
    )
    print(len(input_dataset), len(preprocessed_dataset))
    dataset_size = len(preprocessed_dataset)

    embeddings = list()
    for row_id in tqdm(range(dataset_size)):
        emb = dict()
        for key in ['chosen', 'rejected']:
            tokens = tokenizer.pad(
                {"input_ids": preprocessed_dataset[row_id][f"input_ids_{key}"]},
                padding=True, pad_to_multiple_of=64, return_tensors="pt"
            )
            token_length = len(preprocessed_dataset[row_id][f"input_ids_{key}"])
            input_ids = tokens["input_ids"].unsqueeze(0).to("cuda")
            attention_mask = tokens["attention_mask"].unsqueeze(0).to("cuda")
            with torch.no_grad():
                last_hidden_state = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    output_hidden_states=True
                ).hidden_states[-1]
                emb[f"embedding_{key}"] = last_hidden_state[0][token_length - 1].float().cpu().numpy()
            # with torch.no_grad():
            #     hs = model(
            #         input_ids=input_ids,
            #         attention_mask=attention_mask,
            #         output_hidden_states=True
            #     ).hidden_states[-1]  # [1, seq_len, dim]

            #     # masked mean pooling
            #     mask = attention_mask.unsqueeze(-1).to(hs.dtype)  # [1, seq_len, 1]
            #     summed = (hs * mask).sum(dim=1)                   # [1, dim]
            #     denom = mask.sum(dim=1).clamp(min=1e-6)           # [1, 1]
            #     pooled = (summed / denom).squeeze(0)              # [dim]
            #     emb[f"embedding_{key}"] = pooled.float().cpu().numpy()

        embeddings.append(emb)
    output_dataset = input_dataset.add_column("embeddings", embeddings)
    return output_dataset


def generate_contexts(args, input_dataset):
    # Generate context without survey question pool
    output_dir = os.path.join(args.output_dir, f"{args.model_type}", f"{args.data_subset}")
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    dataset_size = len(input_dataset)

    K = 1  # repeat samples for K times
    dataset_list = list()
    for idx in range(K):
        context_dataset = deepcopy(input_dataset)
        context_lengths = [8] * dataset_size
        if "context_length" in context_dataset.column_names:
            context_dataset = context_dataset.remove_columns("context_length")
        context_dataset = context_dataset.add_column("context_length", context_lengths)
        contexts = list()
        for row_id in tqdm(range(dataset_size)):  # iterate over all samples in original dataset
            row_contexts = list()
            num_context = 0
            controversial_subset = input_dataset.filter(lambda example: example['controversial'] == True)
            if len(controversial_subset) == 0:
                # [NEW] Fallback: use all data as candidates if no controversial items found
                controversial_subset = input_dataset
            controversial_size = len(controversial_subset)
            while num_context < context_lengths[row_id]:
                random_id = np.random.randint(controversial_size)
                context_id = controversial_subset[random_id]['Index']
                context_data = controversial_subset[random_id]
                if not args.synthetic_dataset:
                    if input_dataset[row_id]['prompt'] == context_data['prompt']:
                        continue
                if not args.with_embeddings:
                    row_contexts.append({
                        'original_id': context_id,
                        'chosen': context_data['chosen'],
                        'rejected': context_data['rejected'],
                    })
                else:
                    row_contexts.append({
                        'original_id': context_id,
                        'embedding_chosen': context_data['embeddings']['embedding_chosen'],
                        'embedding_rejected': context_data['embeddings']['embedding_rejected'],
                    })
                num_context += 1
            contexts.append(row_contexts)
        context_dataset = context_dataset.add_column("contexts", contexts)
        dataset_list.append(context_dataset)

    output = concatenate_datasets(dataset_list)
    output.to_json(os.path.join(output_dir, f"{args.data_split}.jsonl"))
    return output


if __name__ == "__main__":
    # default setting on HH-RLHF dataset, please iterate over data subsets and data splits
    seed = 0
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    parser = HfArgumentParser(ScriptArguments)
    script_args: ScriptArguments = parser.parse_args_into_dataclasses()[0]
    print(script_args)
    dataset = generate_embeddings_with_llm(script_args)
    generate_contexts(script_args, dataset)
